### ISSUE TITLE
Testing exploratorio del front end - Marcelo

### ISSUE THREAD

**Issue by andrujuanoo** [figlesias221/ProyectoDevOps_Grupo3_IglesiasPerezMolinoloJuan#14]
Integrante: Marcelo
Esfuerzo en HS-P:
- Estimado: 0 (no hay estimaciones la primera iteración)
- Real: 4

**Comment by mperezjodal** [comment]
Esfuerzo en HS-P:
ESTIMADO: 0 (no hay estimaciones la primera iteración)
REAL: 4
